### ISSUE TITLE
Could not find a valid dependency tree configuration

### ISSUE THREAD

**Issue by SaurabhTotey** [Extrawurst/DerelictSteamworks#1]
Whenever I try and build my sample project with `dub build`, the build fails with the message, `Could not find a valid dependency tree configuration: Package derelict-steamworks contains invalid dependency derelict-util (no version candidates)`. I have `"derelict-glfw3": "~>4.0.0-alpha.6"` and `"derelict-steamworks": "~>0.0.8"` in my dub.json dependencies.

**Comment by extrawurst** [comment]
That's weird, last time I checked it worked for me. But I am on vacation right now without my laptop so I can check it out earliest next Monday :(

**Comment by SaurabhTotey** [comment]
Ok, sounds great.

**Comment by extrawurst** [comment]
ok so this boils down to the package not being compatible with the new derelict-util version. i will look into that

**Comment by extrawurst** [comment]
there seems to be an error in how dub handles configruations. 
@SaurabhTotey  please try to add `subConfiguration "derelict-glfw3" "derelict-glfw3-dynamic"` to your dub.sdl - i have no clue how to pour this into a bug ticket in dub though 😢

**Comment by SaurabhTotey** [comment]
Huh, so I tried rebuilding with `dub build`, and the build is happening successfully. I don't know why it is working now, as I haven't changed anything on my end. Thanks for the support, though.
